export const dataOfBlogs = [
    {
        id: 1,
        date: ["2023-12-12", "DECEMBER 12, 2023"],
        title: "Beginning My Coding Journey",
        text: "I'm excited to start my coding journey as a front-end developer! After months of learning the basics of HTML, CSS, and JavaScript, I'm finally ready to build my own projects and dive deeper into the world of web development.",
        src: "/images/blog-img-one.jpg",
    },
    {
        id: 2,
        date: ["2024-01-15", "JANUARY 15, 2024"],
        title: "Mastering Responsive Design",
        text: "Responsive design has been one of the most rewarding parts of front-end development. Learning how to make websites adapt to any screen size has opened up a world of possibilities for my projects.",
        src: "/images/blog-img-two.jpg",
    },
    {
        id: 3,
        date: ["2024-02-08", "FEBRUARY 8, 2024"],
        title: "Exploring JavaScript Libraries",
        text: "After diving into vanilla JavaScript, I've started exploring libraries like React and Vue. These tools are making my web development process more efficient, and I'm excited to build more interactive websites with them.",
        src: "/images/blog-img-three.png",
    },
    {
        id: 4,
        date: ["2024-03-22", "MARCH 22, 2024"],
        title: "Debugging: My New Superpower",
        text: "Learning to debug effectively has become a crucial skill. Every time I solve a bug, I feel like I'm becoming a stronger developer. Debugging challenges make me learn faster and improve my problem-solving skills.",
        src: "/images/blog-img-four.png",
    },
    {
        id: 5,
        date: ["2024-04-17", "APRIL 17, 2024"],
        title: "Designing With UX in Mind",
        text: "User experience (UX) is a key element in front-end development. Designing websites that are easy to navigate and visually appealing is something I’m learning to prioritize in every project.",
        src: "/images/blog-img-five.png",
    },
    {
        id: 6,
        date: ["2024-05-05", "MAY 5, 2024"],
        title: "The Power of CSS Grid and Flexbox",
        text: "CSS Grid and Flexbox have been game-changers for layout design. They allow me to create complex, responsive layouts with less code. I'm always amazed by how these two CSS techniques can simplify web design.",
        src: "/images/blog-img-six.png",
    },
    {
        id: 7,
        date: ["2024-06-12", "JUNE 12, 2024"],
        title: "Learning Version Control with Git",
        text: "Git is essential for collaboration and version control. As I start working on more complex projects, learning how to use Git and GitHub has been an important step in becoming a professional developer.",
        src: "/images/blog-img-seven.jpg",
    },
    {
        id: 8,
        date: ["2024-07-25", "JULY 25, 2024"],
        title: "Improving My JavaScript Skills",
        text: "As I continue learning front-end development, I’ve been focusing more on JavaScript. Understanding concepts like DOM manipulation, event handling, and API fetching has been both exciting and challenging.",
        src: "/images/blog-img-eight.jpg",
    },
    {
        id: 9,
        date: ["2024-08-19", "AUGUST 19, 2024"],
        title: "Reflecting on My Development Journey",
        text: "As I reflect on my development journey so far, I realize how much I’ve learned. From mastering HTML and CSS to diving into JavaScript frameworks, I’m excited about how far I’ve come and where this path will take me.",
        src: "/images/blog-img-nine.jpg",
    },
];
